### ISSUE TITLE
Mac 2.0 update broke mesh and material editing on voxel objects.

### ISSUE THREAD

**Issue by BenjaminRasmussen** [ClarkThyLord/Voxel-Core#34]
As title says. im on a Mac on godot version 3.2.1 and voxelcore 2.0.0. I can confirm that updating a voxelcore's shader material won't save persistently however it applies it perfectly (?). And whenever I try to manually see mesh options the entire node deselects on the editor tree indicating a thread crash.

**Comment by ClarkThyLord** [comment]
The material / shader persistence issue you're describing should of been fixed in the latest version of Voxel-Core, as of e3e1a527497f9c072b38d02a8463395712d4b1bf, however the Godot Asset Store still hasn't approved the latest release of Voxel-Core, but you can always [update Voxel-Core manually](https://github.com/ClarkThyLord/Voxel-Core#download--clone)

As for the second issue, I'm not familiar with it, however I can tell you that when editing a VoxelObject it's deselected temporarily so as to "isolate" the VoxelObject and prevent unwanted actions, to toggle edit mode you can press space bar or press on the Lock button in the editor ui

Sorry, for the late reply 😅

**Comment by ClarkThyLord** [comment]
Voxel-Core 2.0.3 has been approved by the Godot Asset Library so this issue, along with many others, should be resolved, will close this issue unless otherwise
