### ISSUE TITLE
VoxelObject Menu closing after modfiying voxels in VoxelSet

### ISSUE THREAD

**Issue by theo97490** [ClarkThyLord/Voxel-Core#48]
Hello i have a rather annoying issue. After modifying things in the VoxelSet menu of an VoxelMesh such as adding/removing/modifying voxels, if i go to the VoxelObject and click on edit mode, voxel raycast or update button the voxel menu disapears. Here is a video showing the problem.

https://user-images.githubusercontent.com/56770939/121010013-233a2600-c795-11eb-82fd-2b5fba433aa3.mp4

**Comment by ClarkThyLord** [comment]
Ah yes, this is a very annoying bug I'm very familiar with, when I was debugging it I found that it occurs when trying to edit a VoxelObject via the editor with a sub resource selected. You do the same here when you select the Mesh and VoxelSet. You can "fix" this by unselecting the sub resource, but this isn't really a permanent fix 😕

I've already tried debugging this but wasn't able to find a permanent fix for this because of the way the VoxelObject Editor is called on, but I'll continue to debug I'm sure I'll come up with something 👍 

Sorry for the late response 😓

**Comment by ClarkThyLord** [comment]
Took a look, and was able to figure out a patch 🙌 

I've now merged the patch, let me know if that resolved the encountered issue, thanks.

**Comment by ClarkThyLord** [comment]
Fixed now, as reported in #52
